import { User } from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "محمد محمود",
    email: "mohamedahmed@gmail.com",
    phone: "01012345678",
    location: "القاهرة",
    role: "student",
    coursesCount: 5,
    completedCoursesCount: 3,
    certificatesCount: 2,
    learningHours: 50,
    joinDate: "30-12-2025",
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=1",
    enrolledCourses: [
      { id: "c1", name: "تصميم واجهات المستخدم Ui & Ux", progress: 80, status: 'ongoing' },
      { id: "c2", name: "تصميم واجهات المستخدم Ui & Ux", progress: 80, status: 'ongoing' },
      { id: "c3", name: "تصميم واجهات المستخدم Ui & Ux", progress: 80, status: 'ongoing' },
      { id: "c4", name: "تصميم واجهات المستخدم Ui & Ux", progress: 80, status: 'ongoing' },
      { id: "c5", name: "تصميم واجهات المستخدم Ui & Ux", progress: 80, status: 'ongoing' },
    ]
  },
  {
    id: "2",
    name: "محمد محمود",
    email: "abdelrahmanmahmoudd@gmail.com",
    role: "student",
    coursesCount: 9,
    joinDate: "10-10-2025",
    status: "inactive",
  },
  {
    id: "3",
    name: "أحمد محمد",
    email: "abdelrahmanmahmoudd@gmail.com",
    role: "student",
    coursesCount: 12,
    joinDate: "10-10-2025",
    status: "pending",
  },
  {
    id: "4",
    name: "اسلام مصطفى",
    email: "abdelrahmanmahmoudd@gmail.com",
    role: "instructor",
    coursesCount: 5,
    joinDate: "10-10-2025",
    status: "active",
  },
  {
    id: "5",
    name: "كريم عادل",
    email: "abdelrahmanmahmoudd@gmail.com",
    role: "student",
    coursesCount: 18,
    joinDate: "10-10-2025",
    status: "under_review",
  },
  {
    id: "6",
    name: "محمد أحمد",
    email: "abdelrahmanmahmoudd@gmail.com",
    role: "instructor",
    coursesCount: 8,
    joinDate: "10-10-2025",
    status: "inactive",
  },
  {
    id: "7",
    name: "صلاح أشرف",
    email: "abdelrahmanmahmoudd@gmail.com",
    role: "instructor",
    coursesCount: 2,
    joinDate: "10-10-2025",
    status: "pending",
  },
  {
    id: "8",
    name: "أحمد حسام الدين",
    email: "abdelrahmanmahmoudd@gmail.com",
    role: "student",
    coursesCount: 10,
    joinDate: "10-10-2025",
    status: "under_review",
  },
  {
    id: "9",
    name: "عبد الرحمن أشرف",
    email: "abdelrahmanmahmoudd@gmail.com",
    role: "student",
    coursesCount: 3,
    joinDate: "10-10-2025",
    status: "active",
  },
];
