import { LiveSession } from './types';

export const liveSessions: LiveSession[] = [
  {
    id: 1,
    slug: 'advanced-banking-expansion',
    title: 'توسيع البنى الحديثة: من الخدمة الأحادية إلى الخدمات المصغرة',
    instructor: 'أحمد منتصر',
    instructorRole: 'مهندس برمجيات أول في TechEgypt',
    instructorAvatar: '/profile.jpg',
    image: '/liveCard.png',
    category: 'live',
    description:
      'في هذه الجلسة نستعرض الرحلة العملية لتطوير الأنظمة الكبيرة من بنية تقليدية إلى خدمات مصغرة، مع التركيز على التدرج السليم، مراقبة الأداء، وإدارة المخاطر أثناء التحول.',
    dateLabel: '21 أبريل 2026',
    timeLabel: '8:00 ص - 9:30 ص بتوقيت القاهرة',
    startTime: '2026-04-21T08:00:00+02:00',
    endTime: '2026-04-21T09:30:00+02:00',
    viewers: 1243,
    durationLabel: '42:15',
    resources: [
      { id: 'slides-pdf', name: 'عرض الجلسة.pdf', type: 'pdf' },
      { id: 'slides-link', name: 'رابط الملفات', type: 'link' },
    ],
    speakers: [
      { name: 'Mrs Modupe Oifaemi', role: 'CEO GITECH' },
      { name: 'Dr Alan Smith', role: 'HEAD OF INNOVATION, NJT' },
      { name: 'Stella Johnson', role: 'CFO CLOUDCORE' },
    ],
    messages: [
      {
        id: 'm1',
        authorId: 'instructor-1',
        author: 'أحمد منتصر',
        avatar: '/profile.jpg',
        text: 'ركزوا على أن قرار الانتقال إلى الخدمات المصغرة لازم يكون مبني على احتياج فعلي، وليس مجرد ترند.',
        role: 'instructor',
        createdAt: '2026-04-21T08:04:00+02:00',
      },
      {
        id: 'm2',
        authorId: 'student-1',
        author: 'سارة علي',
        avatar: '/profile.jpg',
        text: 'الجزء الخاص بتقسيم الدومين مهم جداً، خصوصاً مع الأنظمة الكبيرة.',
        role: 'student',
        createdAt: '2026-04-21T08:06:00+02:00',
      },
      {
        id: 'm3',
        authorId: 'student-2',
        author: 'محمود رجب',
        avatar: '/profile.jpg',
        text: 'هل سيتم رفع المادة العلمية بعد انتهاء البث؟',
        role: 'student',
        createdAt: '2026-04-21T08:07:00+02:00',
      },
      {
        id: 'm4',
        authorId: 'instructor-1',
        author: 'أحمد منتصر',
        avatar: '/profile.jpg',
        text: 'نعم، سيتم رفع الملفات والروابط بعد الجلسة مباشرة داخل صفحة الحصة.',
        role: 'instructor',
        createdAt: '2026-04-21T08:09:00+02:00',
      },
    ],
    questions: [
      {
        id: 'q1',
        authorId: 'student-3',
        author: 'منة أحمد',
        avatar: '/profile.jpg',
        text: 'متى يكون التحول إلى microservices قراراً خاطئاً لفريق صغير؟',
        role: 'student',
        createdAt: '2026-04-21T08:10:00+02:00',
        addressedTo: 'instructor',
        status: 'open',
      },
      {
        id: 'q2',
        authorId: 'student-4',
        author: 'عمر السيد',
        avatar: '/profile.jpg',
        text: 'هل تنصحون باستخدام event-driven architecture من البداية أم بعد الوصول لمرحلة معينة؟',
        role: 'student',
        createdAt: '2026-04-21T08:13:00+02:00',
        addressedTo: 'instructor',
        status: 'open',
      },
    ],
    polls: [
      {
        id: 'poll-1',
        authorId: 'instructor-1',
        author: 'أحمد منتصر',
        avatar: '/profile.jpg',
        question: 'ما هي البنية التي تستخدمها حالياً؟',
        role: 'instructor',
        createdAt: '2026-04-21T08:14:00+02:00',
        status: 'live',
        options: [
          { id: 'poll-1-option-1', label: 'نظام متكامل', votes: 42 },
          { id: 'poll-1-option-2', label: 'مايكروسيرفس', votes: 58 },
        ],
      },
    ],
  },
  {
    id: 2,
    slug: 'design-systems-live',
    title: 'تصميم أنظمة واجهات قابلة للتوسع داخل فرق المنتج',
    instructor: 'أحمد منتصر',
    instructorRole: 'مهندس برمجيات أول في TechEgypt',
    instructorAvatar: '/profile.jpg',
    image: '/liveCard.png',
    category: 'live',
    description:
      'جلسة مباشرة حول بناء design system عملي، إدارة المكونات المشتركة، وضبط العلاقة بين المنتج والتصميم والهندسة في فرق متعددة.',
    dateLabel: '15 نوفمبر 2026',
    timeLabel: '8:00 ص - 9:30 م بتوقيت القاهرة',
    startTime: '2026-11-15T20:00:00+02:00',
    endTime: '2026-11-15T21:30:00+02:00',
    viewers: 987,
    durationLabel: '18:40',
    resources: [
      { id: 'design-pdf', name: 'Design System Guide.pdf', type: 'pdf' },
      { id: 'design-link', name: 'Figma Library', type: 'link' },
    ],
    speakers: [
      { name: 'Mrs Modupe Oifaemi', role: 'CEO GITECH' },
      { name: 'Dr Alan Smith', role: 'HEAD OF INNOVATION, NJT' },
      { name: 'Stella Johnson', role: 'CFO CLOUDCORE' },
    ],
    messages: [
      {
        id: 'd1',
        authorId: 'instructor-2',
        author: 'أحمد منتصر',
        avatar: '/profile.jpg',
        text: 'أهم نقطة في design system هي وضوح قواعد الاستخدام، وليس فقط شكل المكون.',
        role: 'instructor',
        createdAt: '2026-11-15T20:05:00+02:00',
      },
      {
        id: 'd2',
        authorId: 'student-5',
        author: 'ياسمين خالد',
        avatar: '/profile.jpg',
        text: 'هل تنصح بتقسيم المكونات حسب domain أم حسب atomic design؟',
        role: 'student',
        createdAt: '2026-11-15T20:08:00+02:00',
      },
    ],
    questions: [
      {
        id: 'dq1',
        authorId: 'student-6',
        author: 'عبدالله هاني',
        avatar: '/profile.jpg',
        text: 'ما أفضل طريقة لتوثيق variants بدون ما تصبح الوثائق نفسها مرهقة؟',
        role: 'student',
        createdAt: '2026-11-15T20:12:00+02:00',
        addressedTo: 'instructor',
        status: 'open',
      },
    ],
    polls: [
      {
        id: 'dpoll-1',
        authorId: 'instructor-2',
        author: 'أحمد منتصر',
        avatar: '/profile.jpg',
        question: 'ما أكثر شيء يعطل adoption للـ design system داخل فريقك؟',
        role: 'instructor',
        createdAt: '2026-11-15T20:15:00+02:00',
        status: 'ended',
        options: [
          { id: 'dpoll-1-option-1', label: 'ضعف التوثيق', votes: 21 },
          { id: 'dpoll-1-option-2', label: 'عدم التزام الفريق', votes: 34 },
          { id: 'dpoll-1-option-3', label: 'بطء تحديث المكونات', votes: 17 },
        ],
      },
    ],
  },
  {
    id: 3,
    slug: 'frontend-architecture',
    title: 'هندسة واجهات Frontend قابلة للتوسع',
    instructor: 'محمد علي',
    instructorRole: 'Senior Frontend Engineer',
    instructorAvatar: '/profile.jpg',
    image: '/card.jpg',
    category: 'upcoming',
    description: 'جلسة قادمة لمناقشة تنظيم المجلدات، الأنماط المعمارية، والحد من التضخم داخل صفحات Next.js.',
    startTime: '2026-04-21T10:30:00+02:00',
  },
  {
    id: 4,
    slug: 'ai-product-strategy',
    title: 'استراتيجية بناء منتجات AI قابلة للإطلاق',
    instructor: 'فاطمة علي',
    instructorRole: 'AI Product Manager',
    instructorAvatar: '/profile.jpg',
    image: '/card.jpg',
    category: 'upcoming',
    description: 'كيف تنقل الفكرة إلى MVP ثم إلى منتج حقيقي مع قياس القيمة وليس الضجيج فقط.',
    startTime: '2026-04-21T13:45:00+02:00',
  },
  {
    id: 5,
    slug: 'mlops-retrospective',
    title: 'مراجعة عملية لتجارب MLOps في فرق متوسطة الحجم',
    instructor: 'فاطمة صالح',
    instructorRole: 'Machine Learning Lead',
    instructorAvatar: '/profile.jpg',
    image: '/liveCard.png',
    category: 'past',
    description: 'جلسة منتهية حول النشر، المراقبة، والتحسين المستمر لنماذج الذكاء الاصطناعي.',
    startTime: '2026-04-19T19:00:00+02:00',
    endTime: '2026-04-19T20:10:00+02:00',
    viewers: 120,
  },
];

export function getSessionBySlug(slug: string) {
  return liveSessions.find((session) => session.slug === slug);
}
