import type { TFunction } from "i18next";
import { LiveSession } from "./types";

function getSpeakers(t: TFunction) {
  return [
    {
      name: t("liveSession.speakers.1.name"),
      role: t("liveSession.speakers.1.role"),
    },
    {
      name: t("liveSession.speakers.2.name"),
      role: t("liveSession.speakers.2.role"),
    },
    {
      name: t("liveSession.speakers.3.name"),
      role: t("liveSession.speakers.3.role"),
    },
  ];
}

export function getLiveSessions(t: TFunction): LiveSession[] {
  return [
    {
      id: 1,
      slug: "advanced-banking-expansion",
      title: t("liveSession.records.1.title"),
      instructor: t("liveSession.records.1.instructor"),
      instructorRole: t("liveSession.records.1.instructorRole"),
      instructorAvatar: "/profile.jpg",
      image: "/liveCard.png",
      category: "live",
      description: t("liveSession.records.1.description"),
      dateLabel: t("liveSession.records.1.dateLabel"),
      timeLabel: t("liveSession.records.1.timeLabel"),
      startTime: "2026-04-21T08:00:00+02:00",
      endTime: "2026-04-21T09:30:00+02:00",
      viewers: 1243,
      durationLabel: "42:15",
      resources: [
        { id: "slides-pdf", name: t("liveSession.records.1.resources.1"), type: "pdf" },
        { id: "slides-link", name: t("liveSession.records.1.resources.2"), type: "link" },
      ],
      speakers: getSpeakers(t),
      messages: [
        {
          id: "m1",
          authorId: "instructor-1",
          author: t("liveSession.records.1.instructor"),
          avatar: "/profile.jpg",
          text: t("liveSession.records.1.messages.1"),
          role: "instructor",
          createdAt: "2026-04-21T08:04:00+02:00",
        },
        {
          id: "m2",
          authorId: "student-1",
          author: t("liveSession.records.1.messageAuthors.1"),
          avatar: "/profile.jpg",
          text: t("liveSession.records.1.messages.2"),
          role: "student",
          createdAt: "2026-04-21T08:06:00+02:00",
        },
        {
          id: "m3",
          authorId: "student-2",
          author: t("liveSession.records.1.messageAuthors.2"),
          avatar: "/profile.jpg",
          text: t("liveSession.records.1.messages.3"),
          role: "student",
          createdAt: "2026-04-21T08:07:00+02:00",
        },
        {
          id: "m4",
          authorId: "instructor-1",
          author: t("liveSession.records.1.instructor"),
          avatar: "/profile.jpg",
          text: t("liveSession.records.1.messages.4"),
          role: "instructor",
          createdAt: "2026-04-21T08:09:00+02:00",
        },
      ],
      questions: [
        {
          id: "q1",
          authorId: "student-3",
          author: t("liveSession.records.1.questionAuthors.1"),
          avatar: "/profile.jpg",
          text: t("liveSession.records.1.questions.1"),
          role: "student",
          createdAt: "2026-04-21T08:10:00+02:00",
          addressedTo: "instructor",
          status: "open",
        },
        {
          id: "q2",
          authorId: "student-4",
          author: t("liveSession.records.1.questionAuthors.2"),
          avatar: "/profile.jpg",
          text: t("liveSession.records.1.questions.2"),
          role: "student",
          createdAt: "2026-04-21T08:13:00+02:00",
          addressedTo: "instructor",
          status: "open",
        },
      ],
      polls: [
        {
          id: "poll-1",
          authorId: "instructor-1",
          author: t("liveSession.records.1.instructor"),
          avatar: "/profile.jpg",
          question: t("liveSession.records.1.poll.question"),
          role: "instructor",
          createdAt: "2026-04-21T08:14:00+02:00",
          status: "live",
          options: [
            {
              id: "poll-1-option-1",
              label: t("liveSession.records.1.poll.options.1"),
              votes: 42,
            },
            {
              id: "poll-1-option-2",
              label: t("liveSession.records.1.poll.options.2"),
              votes: 58,
            },
          ],
        },
      ],
    },
    {
      id: 2,
      slug: "design-systems-live",
      title: t("liveSession.records.2.title"),
      instructor: t("liveSession.records.2.instructor"),
      instructorRole: t("liveSession.records.2.instructorRole"),
      instructorAvatar: "/profile.jpg",
      image: "/liveCard.png",
      category: "live",
      description: t("liveSession.records.2.description"),
      dateLabel: t("liveSession.records.2.dateLabel"),
      timeLabel: t("liveSession.records.2.timeLabel"),
      startTime: "2026-11-15T20:00:00+02:00",
      endTime: "2026-11-15T21:30:00+02:00",
      viewers: 987,
      durationLabel: "18:40",
      resources: [
        { id: "design-pdf", name: t("liveSession.records.2.resources.1"), type: "pdf" },
        { id: "design-link", name: t("liveSession.records.2.resources.2"), type: "link" },
      ],
      speakers: getSpeakers(t),
      messages: [
        {
          id: "d1",
          authorId: "instructor-2",
          author: t("liveSession.records.2.instructor"),
          avatar: "/profile.jpg",
          text: t("liveSession.records.2.messages.1"),
          role: "instructor",
          createdAt: "2026-11-15T20:05:00+02:00",
        },
        {
          id: "d2",
          authorId: "student-5",
          author: t("liveSession.records.2.messageAuthors.1"),
          avatar: "/profile.jpg",
          text: t("liveSession.records.2.messages.2"),
          role: "student",
          createdAt: "2026-11-15T20:08:00+02:00",
        },
      ],
      questions: [
        {
          id: "dq1",
          authorId: "student-6",
          author: t("liveSession.records.2.questionAuthors.1"),
          avatar: "/profile.jpg",
          text: t("liveSession.records.2.questions.1"),
          role: "student",
          createdAt: "2026-11-15T20:12:00+02:00",
          addressedTo: "instructor",
          status: "open",
        },
      ],
      polls: [
        {
          id: "dpoll-1",
          authorId: "instructor-2",
          author: t("liveSession.records.2.instructor"),
          avatar: "/profile.jpg",
          question: t("liveSession.records.2.poll.question"),
          role: "instructor",
          createdAt: "2026-11-15T20:15:00+02:00",
          status: "ended",
          options: [
            {
              id: "dpoll-1-option-1",
              label: t("liveSession.records.2.poll.options.1"),
              votes: 21,
            },
            {
              id: "dpoll-1-option-2",
              label: t("liveSession.records.2.poll.options.2"),
              votes: 34,
            },
            {
              id: "dpoll-1-option-3",
              label: t("liveSession.records.2.poll.options.3"),
              votes: 17,
            },
          ],
        },
      ],
    },
    {
      id: 3,
      slug: "frontend-architecture",
      title: t("liveSession.records.3.title"),
      instructor: t("liveSession.records.3.instructor"),
      instructorRole: t("liveSession.records.3.instructorRole"),
      instructorAvatar: "/profile.jpg",
      image: "/card.jpg",
      category: "upcoming",
      description: t("liveSession.records.3.description"),
      startTime: "2026-04-21T10:30:00+02:00",
    },
    {
      id: 4,
      slug: "ai-product-strategy",
      title: t("liveSession.records.4.title"),
      instructor: t("liveSession.records.4.instructor"),
      instructorRole: t("liveSession.records.4.instructorRole"),
      instructorAvatar: "/profile.jpg",
      image: "/card.jpg",
      category: "upcoming",
      description: t("liveSession.records.4.description"),
      startTime: "2026-04-21T13:45:00+02:00",
    },
    {
      id: 5,
      slug: "mlops-retrospective",
      title: t("liveSession.records.5.title"),
      instructor: t("liveSession.records.5.instructor"),
      instructorRole: t("liveSession.records.5.instructorRole"),
      instructorAvatar: "/profile.jpg",
      image: "/liveCard.png",
      category: "past",
      description: t("liveSession.records.5.description"),
      startTime: "2026-04-19T19:00:00+02:00",
      endTime: "2026-04-19T20:10:00+02:00",
      viewers: 120,
    },
  ];
}

export function getSessionBySlug(slug: string, t: TFunction) {
  return getLiveSessions(t).find((session) => session.slug === slug);
}
